---
#####
# Used to configure yamlling so it skips some checks
# But also some files too
#####
extends: default

rules:
  line-length: disable
#  comments: disable
  comments-indentation: disable
  document-start: disable
  indentation: disable

ignore: |
  lovelace-ui.yaml
  custom_components/
  .git
  .github/workflows/yaml-lint.yaml
  themes/
