# Describes the format for available ADS services
update_gtfs:
  name: Update/create GTFS Data
  description: Unpacks source to gtfs-db
  fields:
    extract_from:
      name: Indicate source of the data 
      description: Select if you update from url or zip
      required: true
      example: "url"
      default: "url"
      selector:
        select:
          translation_key: "extract_from"
          options:
            - "url"
            - "zip"
    file:
      name: Name of the transport service, without .zip
      description: If you use the same name as an existing one, the existing one will be overwitten
      required: true
      example: "mytransportservice"
      selector:
        text:            
    url:
      name: URL
      description: provide the full path to the zip file itself
      required: true
      default: "na"
      example: "https://path-to-my-zip-file-location/filename.zip"
      selector:
        text:            
    clean_feed_info:
      name: Remove feed-info
      description: Removes feed_info.txt from zip (use in case file content incorrect)
      required: true
      default: false
      selector:
        boolean: 


update_gtfs_rt_local:
  name: Update GTFS Realtime Data locally
  description: Downloads realtime data locally
  fields:
    file:
      name: Name of the transport service with realtime data
      description: Preferably use the same name as for static data
      required: true
      example: "mytransportservice"
      selector:
        text:            
    url:
      name: URL
      description: provide the full path to the zip file itself
      required: true
      default: "na"
      example: "https://path-to-my-realttime-data"
      selector:
        text:
    api_key:
      name: api_key
      description: provide api_key if required
      required: false
      selector:
        text:        
    x_api_key:
      name: x_api_key
      description: provide x_api_key if required
      required: false
      selector:
        text:  
    ocp_apim_subscription_key:
      name: Ocp-Apim-Subscription-Key
      description: provide Ocp-Apim if required
      required: false
      selector:
        text:         
    api_key_location:
      name: Indicate location of the key
      description: Select location of the key
      required: true      
      default: "not_applicable"
      example: "not_applicable"
      selector:
        select:
          translation_key: "api_key_location"
          options:
            - "not_applicable"
            - "header"
            - "query_string"     
    accept:
      name: Accept
      description: add application/protobuf to the header
      default: false
      required: true      
      selector:
        boolean: 
      
    debug_output:
      name: Save all to local file in readable format
      description: for debug purposes, see /config/www/gtfs2
      required: true
      default: false
      selector:
        boolean:         
        
update_gtfs_local_stops: 
  name: Update Local Stops
  description: Updates local stops based on location entity
  fields:       
    entity_id:
      name: Entity
      description: Select person or zone to update stops for
      required: true
      example: "zone.home"
      selector:
        entity:
          domain: ["person", "zone"]          